on: [push]


jobs:
  custom_test:

    runs-on: ubuntu-latest

    name: We test it locally with act
    steps:
      - name: Get Pokemon name
        uses: hyunsungK/github-action-test@master
        id: pokemon
        with:
          pokemon_id: 150

      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
